Django/TCC_Polaris/WebSite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # -----> USER PAGE
    path('',views.index,name='index'),
    path('sobre/',views.sobre,name='sobre'),
    path('dicas/',views.dicas,name='dicas'),
    path('faq/',views.faq,name='faq'),
    path('termos/',views.termos,name='termos'),
    path('politica/',views.politica,name='politica'),
    path('catalogo/', views.catalogo, name='catalogo'),
    # -----> ESQUECI MINHA SENHA
    path('esqueci_senha/', views.esqueci_senha, name='esqueci_senha'),
    # -----> CHECKOUT
    path('efetuar_compra/<int:produto_id>/', views.efetuar_compra, name='efetuar_compra'),
    # -----> ADMIN PAGE
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_fotos/', views.add_fotos, name='add_fotos'),
    path('add_user/', views.add_user, name='add_user'),
    path('consulta_fotos/', views.consulta_fotos, name='consulta_fotos'),
    path('consulta_users/', views.consulta_users, name='consulta_users'),
    # -----> LOGIN AUTH
    path('login', views.login_view, name="login"),
    path('register', views.register_view, name="register"),
    path('logout', views.logout_view, name="logout"),
    # -----> CRUD FOTOS
    path('listarFotos', views.listarFotos, name="listarFotos"),
    path('editar_fotos/<int:id>', views.edit_fotos, name="edit_fotos"),
    path('atualizar_fotos/<int:id>', views.update_fotos, name="update_fotos"),
    path('deletar_fotos/<int:id>', views.delete_fotos, name="delete_fotos"),
    # -----> CRUD USER
    path('listarUsers', views.listarUsers, name="listarUsers"),
    path('editar_user/<int:id>', views.edit_user, name="edit_user"),
    path('atualizar_user/<int:id>', views.update_user, name="update_user"),
    path('deletar_user/<int:id>', views.delete_user, name="delete_user"),
]

Django/TCC_Polaris/setup/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Website.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/TCC_Polaris/WebSite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

GENERO = (
    ('Masculino','Masculino'),
    ('Feminino','Feminino'),
    ('Unisex','Unisex'),
)

class Tamanho_BD(models.Model):
    tamanho = models.CharField(max_length=7)
    def __str__(self):
        return self.tamanho

class Marca_BD(models.Model):
    marca = models.CharField(max_length=15)
    def __str__(self):
        return self.marca

class Tipo_BD(models.Model):
    tipo = models.CharField(max_length=15)
    def __str__(self):
        return self.tipo

class Tecido_BD(models.Model):
    tecido = models.CharField(max_length=15)
    def __str__(self):
        return self.tecido

class Produtos_BD(models.Model):
    titulo = models.CharField(max_length=25)
    foto = models.ImageField(upload_to= 'images/')
    descricao = models.TextField(max_length=255)
    preco = models.DecimalField(max_digits=5, decimal_places=2)
    genero = models.CharField(max_length = 20, choices = GENERO, default = 'Unisex')
    tamanho = models.ForeignKey(Tamanho_BD, on_delete=models.CASCADE)
    tipo = models.ForeignKey(Tipo_BD, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca_BD, on_delete=models.CASCADE)
    tecido = models.ForeignKey(Tecido_BD, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    data_foto = models.DateField(default=timezone.now)
    
#-----Imagem da Barra de Pesquisa
class Barra_Pesquisa(models.Model):
    imagem = models.ImageField(upload_to= 'images/')

# * ATENÇÃO ESTA PARTE DAS MODELS VAI FAZER O CHECKOUT, OU SEJA AS COMPRAS *
# * ATENÇÃO, O NOME DA CLASSE É 'PEDIDO' E EFETUA A FUNÇÃO DE CHECKOUT *
# * ATENÇÃO ESTA FASE ANDA ESTÁ EM FASE DE TESTES!! *
class Pedido(models.Model):
    produto = models.ForeignKey(Produtos_BD, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    email = models.EmailField()
    endereco_entrega = models.TextField()
    quantidade = models.PositiveIntegerField(default=1)
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    data_pedido = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Calcule o total com base na quantidade e preço do produto
        self.total = self.produto.preco * self.quantidade
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Pedido de {self.produto.titulo} por {self.nome}"

Django/TCC_Polaris/WebSite/views.py
from django.contrib import messages
from django.contrib import auth
from django.http import HttpResponseForbidden
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404, redirect
from Website.forms import ProdutosForms, CheckoutForm, LoginForms, RegisterForms, UserForms
from .models import Barra_Pesquisa, Pedido, Produtos_BD, Tipo_BD, Marca_BD, Tecido_BD, Tamanho_BD, GENERO
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, EmptyPage
from django.urls import reverse

# ------> VERIFICADORES
def is_admin(user):
    return user.is_staff

def admin_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_staff:
            return render(
                request,
                'error_page.html',
                {'error_message': "Você não tem permissão para acessar esta página."}
            )
        return view_func(request, *args, **kwargs)

    return _wrapped_view

# -----> USER PAGE
def index(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'index.html', {'register_form':register_form,'user_form': login_form , 'fotos': fotos_view,'imagens': imagem_view})

def faq(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'faq.html', {'register_form':register_form,'user_form': login_form ,'fotos': fotos_view,'imagens': imagem_view})

def termos(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'termos.html', {'register_form':register_form,'user_form': login_form ,'fotos': fotos_view,'imagens': imagem_view})

def politica(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'politica.html', {'register_form':register_form,'user_form': login_form ,'fotos': fotos_view,'imagens': imagem_view})

def dicas(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'dicas.html', {'register_form':register_form,'user_form': login_form ,'fotos': fotos_view,'imagens': imagem_view})

def sobre(request):
    fotos_view = Produtos_BD.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()
    return render(request, 'sobre.html', {'register_form':register_form,'user_form': login_form ,'fotos': fotos_view,'imagens': imagem_view})

from django.core.paginator import Paginator, EmptyPage

def catalogo(request):
    # Código do primeiro bloco
    query = request.GET.get('q')
    genero_filter = request.GET.get('genero')
    tipo_filter = request.GET.get('tipo')
    marca_filter = request.GET.get('marca')
    tecido_filter = request.GET.get('tecido')
    tamanho_filter = request.GET.get('tamanho')

    produtos_view = Produtos_BD.objects.all()

    if query:
        produtos_view = produtos_view.filter(titulo__icontains=query)

    if genero_filter:
        produtos_view = produtos_view.filter(genero=genero_filter)

    if tipo_filter:
        produtos_view = produtos_view.filter(tipo__tipo=tipo_filter)

    if marca_filter:
        produtos_view = produtos_view.filter(marca__marca=marca_filter)

    if tecido_filter:
        produtos_view = produtos_view.filter(tecido__tecido=tecido_filter)

    if tamanho_filter:
        produtos_view = produtos_view.filter(tamanho__tamanho=tamanho_filter)

    register_form = RegisterForms()
    login_form = LoginForms()
    imagem_view = Barra_Pesquisa.objects.all()
    user = User.objects.all()

    tipos = Tipo_BD.objects.all()
    marcas = Marca_BD.objects.all()
    tecidos = Tecido_BD.objects.all()
    tamanhos = Tamanho_BD.objects.all()
    generos = [choice[0] for choice in GENERO]

    items_por_pagina = 10  # Altere conforme necessário

    # Obtém o número da página a partir dos parâmetros da solicitação
    page = request.GET.get('page', 1)

    # Cria um objeto Paginator
    paginator = Paginator(produtos_view, items_por_pagina)

    try:
        produtos_paginados = paginator.page(page)
    except EmptyPage:
        # Se a página solicitada estiver fora do intervalo, exibe a última página disponível
        produtos_paginados = paginator.page(paginator.num_pages)

    return render(request, 'catalogo.html', {
        'register_form':register_form,
        'user_form': login_form ,
        'produtos': produtos_paginados,
        'imagens': imagem_view,
        'generos': generos,
        'tipos': tipos,
        'marcas': marcas,
        'tecidos': tecidos,
        'tamanhos': tamanhos,
        'users': user
    })

#   ATENÇÃO ESTA PARTE DAS MODELS EFETUA AS COMPRAS E AINDA ESTÁ SOB FASE DE TESTE   #
def efetuar_compra(request, produto_id):
    produto = get_object_or_404(Produtos_BD, id=produto_id)
    
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            # Crie um novo pedido
            novo_pedido = form.save(commit=False)
            novo_pedido.produto = produto
            novo_pedido.save()

            # Lógica adicional pode ser adicionada aqui, como atualizar o estoque, processar pagamento, etc.

            # Redirecione para a lista de produtos após a compra
            return redirect('catalogo')
    else:
        form = CheckoutForm()
        
    context = {'form': form, 'produto': produto}
    return render(request, 'efetuar_compra.html', {'form': form, 'produto': produto})

#   ATENÇÃO ESTA PARTE TEM A FUNÇÃO DE FAZER A QUANTIDADE DOS PRODUTOS E CRIAR O VALOR TOTAL E AINDA ESTÁ SOB FASE DE TESTE   #

def detalhes_produto(request, produto_id):
    produto = Produtos_BD.objects.get(pk=produto_id)
    pedido = Pedido(produto=produto, quantidade=1)  # Defina outros campos conforme necessário

    context = {
        'produto': produto,
        'pedido': pedido,
    }
    return render(request, 'efetuar_compra.html', context)

# ATENÇÃO ESTE TRECHO SE TRATA DO ESQUECI MINHA SENHA E AINDA ESTÁ SOB TESTE
def esqueci_senha(request):
    # Sua lógica para a recuperação de senha aqui
    return render(request, 'catalogo.html')

# -----> DASHBOARD ADMIN PAGE

@admin_required
def dashboard(request):
    user = User.objects.all()
    fotos_view = Produtos_BD.objects.all()
    return render(request, 'dashboard.html', {'user':user,'fotos': fotos_view})

@admin_required
def consulta_fotos(request):
    user = User.objects.all()
    fotos_view = Produtos_BD.objects.all()
    return render(request, 'dashboardConsulta_fotos.html', {'user':user, 'fotos': fotos_view})

@admin_required
def consulta_users(request):
    user = User.objects.all()
    fotos_view = Produtos_BD.objects.all()
    return render(request, 'dashboardConsulta_user.html', {'user':user, 'fotos': fotos_view})

@admin_required
def add_user(request):
    try:
        if request.method == 'POST':
            register_form = UserForms(request.POST)
            if register_form.is_valid():
                user = register_form.save(commit=False)
                user.save()
                messages.success(request, 'Usuário foi adicionado com sucesso!')
                return redirect('add_user')    
        else:
            register_form = UserForms()
    except Exception as e:
        messages.error(request, e)

    return render(request, 'dashboardAdd_user.html', {'register_form': register_form})

@admin_required
def add_fotos(request):
    if request.method == 'POST':
        foto_form = ProdutosForms(request.POST, request.FILES)
        if foto_form.is_valid():
            foto = foto_form.save(commit=False)
            foto.autor = request.user
            foto.save()
            messages.success(request, 'Produto foi adicionado com sucesso!')
            return redirect('consulta_fotos')
    else:
        foto_form = ProdutosForms()

    return render(request, 'dashboardAdd_fotos.html', {'foto_form': foto_form})

# -----> LOGIN LOGOUT AUTH
def register_view(request):
    if request.method == 'POST':
        register_form = RegisterForms(request.POST)
        if register_form.is_valid():
            email = register_form.cleaned_data.get('email')
            username = register_form.cleaned_data.get('username')
            password = register_form.cleaned_data.get('password')
            user = User.objects.create_user(username=username, email=email, password=password)

            if user is not None:
                user = authenticate(request, username=username, password=password)
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, 'Erro ao efetuar login')
                return redirect('index')
    else:
        register_form = RegisterForms()

    return render(request, 'index.html', {'register_form': register_form})

def login_view(request):
    user_form = LoginForms()

    if request.method == 'POST':
        user_form = LoginForms(request.POST)

    if user_form.is_valid():
        email = user_form['email'].value()
        senha = user_form['senha'].value()

Django/TCC_Polaris/WebSite/templates/catalogo.html
{% extends 'layouts/catalogo.html' %}
{% load static %}
{% block content %}
{% include 'partials/user/catalog/header_catalog.html' %}
{% include 'partials/user/catalog/modals.html' %}  
    <div id="carouselExample" class="carousel slide position-relative">
      <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'assets/img/compre_agora.jpg' %}" class="d-block w-100" alt="...">
              <div class="search-bar-container position-absolute top-50 start-50 translate-middle mt-1">
                  <form class="d-flex" method="GET" action="{% url 'catalogo' %}" >
                      <input class="form-control me-2 search-input" type="search" placeholder="Pesquisar" aria-label="Search" name="q" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #B9C2C4;">
                      <button class="btn-search" type="submit" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #FFFFF5;">Buscar</button>
                  </form>
              </div>
          </div>
      </div>
    </div>
    <header>
        <h1 class="h2" style="font-family: serif; color: #3D3D3D;">Nossos Produtos</h1>
    </header><br>
    <!-- Container -->
    <div class="container pt-1 mt-1">
        <!-- Filtros -->

    <style>
        .form-select {
        background-color: #B9C2C4;
        color: #3D3D3D;
        border: 1px solid #B9C2C4;
        border-radius: 5px;
        font-weight: bold;
        box-shadow: 0 4px 8px #B9C2C4; /* Adicione uma sombra suave */
        transition: box-shadow 0.3s; /* Transição suave para a sombra */
    }

    .form-select:focus {
        outline: none; /* Remova o contorno ao focar no campo de pesquisa */
        box-shadow: 0 0 8px #B9C2C4; /* Altere a sombra ao focar */
    }

    .form-select:hover {
        background-color: #FFFFF5;
        border-color: #947F57;
        outline: none; /* Remova o contorno ao focar no campo de pesquisa */
        box-shadow: 0 0 8px #B9C2C4; /* Altere a sombra ao focar */
    }

    .form-select option {
        background-color: #B9C2C4;
        color: #3D3D3D;
        outline: none; /* Remova o contorno ao focar no campo de pesquisa */
        box-shadow: 0 0 8px #B9C2C4; /* Altere a sombra ao focar */
    }

    .form-select option:hover {
        background-color: #FFFFF5;
        outline: none; /* Remova o contorno ao focar no campo de pesquisa */
        box-shadow: 0 0 8px #B9C2C4; /* Altere a sombra ao focar */
    }
    </style>
        <div class="filter-section">
          <form method="get" action="{% url 'catalogo' %}" class="d-flex justify-content-end">
              <div class="mb-3 me-3">
                  <label for="genero" class="form-label" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Gênero:</label>
                  <select class="form-select" name="genero" id="genero">
                      <option value="" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Todos</option>
                      {% for genero in generos %}
                          <option value="{{ genero }}" {% if genero == genero_filter %}selected{% endif %} style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">{{ genero }}</option>
                      {% endfor %}
                  </select>
              </div>
              <div class="mb-3 me-3">
                  <label for="tipos" class="form-label" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Tipos:</label>
                  <select class="form-select" name="tipo" id="tipo">
                      <option value="" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;" >Todos</option>
                      {% for tipo in tipos %}
                          <option value="{{ tipo }}" {% if tipo == tipo_filter %}selected{% endif %} style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">{{ tipo }}</option>
                      {% endfor %}
                  </select>
              </div>
              <div class="mb-3 me-3">
                  <label for="marca" class="form-label" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Marca:</label>
                  <select class="form-select" name="marca" id="marca">
                      <option value="" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Todos</option>
                      {% for marca in marcas %}
                          <option value="{{ marca }}" {% if marca == marca_filter %}selected{% endif %} style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">{{ marca }}</option>
                      {% endfor %}
                  </select>
              </div>
              <div class="mb-3 me-3">
                  <label for="tecido" class="form-label" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Tecido:</label>
                  <select class="form-select" name="tecido" id="tecido">
                      <option value="" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Todos</option>
                      {% for tecido in tecidos %}
                          <option value="{{ tecido }}" {% if tecido == tecido_filter %}selected{% endif %} style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">{{ tecido }}</option>
                      {% endfor %}
                  </select>
              </div>
              <div class="mb-3 me-3">
                  <label for="tamanho" class="form-label" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Tamanho:</label>
                  <select class="form-select" name="tamanho" id="tamanho">
                      <option value="" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">Todos</option>
                      {% for tamanho in tamanhos %}
                          <option value="{{ tamanho }}" {% if tamanho == tamanho_filter %}selected{% endif %} style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #3D3D3D;">{{ tamanho }}</option>
                      {% endfor %}
                  </select>
              </div>
              <button type="submit" class="mb-3 me-3 btn-ver-mais align-self-end" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #FFFFF5;">Filtrar</button>
          </form>
        </div><br>
   <!-- cards -->
    <div class="row row-cols-1 row-cols-md-5 g-3">
        {% for produto in produtos %}
            <div class="col">
                <div class="card">
                    <img src="{{ produto.foto.url }}" class="card-img-top" alt="{{ produto.titulo }}">
                    <div class="card-body">
                        <h5 class="card-title text-left" style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;  color: #3D3D3D;">{{ produto.titulo }} - <br><span style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;  color: #154734;">R${{ produto.preco }}</span></h5>
                        {% if user.is_authenticated %}  
                            {% csrf_token %}
                            <button type="button" class="btn-ver-mais" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{ produto.id }}">
                                Ver mais
                            </button>
                        {% else %}
                            <!-- Alterações no botão para abrir o modal da sacola -->
                            <button type="button" class="btn-ver-mais" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Ver mais
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Modais Catalogo -->
            <div class="modal fade" id="staticBackdrop{{ produto.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel{{ produto.id }}" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel{{ produto.id }}">{{ produto.titulo }}</h1>
                            <button class="fechar" data-bs-dismiss="modal" aria-label="Close">
                                <span class="icon-close">
                                    <ion-icon name="close"></ion-icon>
                                </span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ produto.foto.url }}" class="card-img-top" alt="{{ produto.titulo }}">
                        </div>
                        <div class="footer-modal">
                            <div>
                                <h1 class="modal-title fs-5" style="font-family: serif; color: #FFFFF5;">{{ produto.descricao }}</h1><br>
                                <h1 class="modal-title fs-5" style="font-family: serif; color: #FFFFF5">R$- {{ produto.preco }}</h1>
                            </div>
                        </div><br>
                        <!-- Corrigir o botão Comprar -->
                        <form method="post" action="{% url 'efetuar_compra' produto_id=produto.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn-ver-mais">
                                Comprar
                            </button>
                        </form><br>
                    </div>
                </div>
            </div>
            <!-- Fim dos Modais Catalogo -->
            {% endfor %}
        </div>
        <!-- cards -->
    <style>
    .page-link {

        margin-left: 10px; /* Margem à esquerda para separação do botão */
        box-shadow: 0 4px 8px #3D3D3D; /* Adicione uma sombra suave */
        transition: background-color 0.3s; /* Transição suave para a cor de fundo */
        background-color: #B9C2C4;
        color: #FFFFF5;
        border: none;
        border-radius: 4px;
        padding: 8px 16px;
        font-size: 1rem;
        cursor: pointer;
        
    }
    .page-link:hover {
        background-color: #947F57;
        text-decoration: none;
    }
    .page-item{
        margin-right: 10px;
    }
    .paginatiot {
        box-shadow: 0 4px 8px #B9C2C4; /* Adicione uma sombra suave */
        transition: box-shadow 0.3s; /* Transição suave para a sombra */
    }
    .page-link:focus {
        outline: none; /* Remova o contorno ao focar no campo de pesquisa */
        box-shadow: 0 4px 8px #B9C2C4; /* Altere a sombra ao focar */
    }

    .page-link {
        background-color: #FFFFF5;
        border-color: #947F57;
    }

    .page-link  {
        background-color: #B9C2C4;
        color:#3D3D3D ;
        border: 1px solid #a7adad;
        border-radius: 5px;
        font-weight: bold;
    }
    </style>

    <!-- Paginator mais polido -->
      <div class="pagination justify-content-center mt-4">
        <ul class="pagination">
          {% if produtos.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page=1">&laquo; first</a>
              </li>
              <li class="page-item">
                  <a class="page-link" href="?page={{ produtos.previous_page_number }}">previous</a>
              </li>
              {% endif %}

              <li class="page-item disabled">
                  <span class="page-link current-page">
                      Página {{ produtos.number }} de {{ produtos.paginator.num_pages }}.
                  </span>
              </li>

              {% if produtos.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ produtos.next_page_number }}" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #FFFFF5;">next</a>
                  </li>
                  <li class="page-item">
                      <a class="page-link" href="?page={{ produtos.paginator.num_pages }}" style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color: #FFFFF5;">last &raquo;</a>
                  </li>
              {% endif %}
          </ul>
        </div>
    </div>
  {% include 'partials/user/footer.html' %}
  {% endblock %}

Django/TCC_Polaris/WebSite/templates/dashboardEditar_fotos.html
{% extends 'layouts/adminbase.html' %}
{% load static %}
{% block content %}
	<!-- for header part -->
	{% include 'partials/admin/header.html' %}
	{% include 'partials/admin/sidebar.html' %}
	<div class="main">
        {% include 'partials/alerts.html' %}
        <form method="POST" action="{% url 'update_fotos' fotos.id %}" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            {{form.as_p}}
            <div class="form-group">
                <label for="id_foto">Foto:</label>
                <img src="{{ fotos.foto.url }}" style="width: 100%;border-top-left-radius: calc(0.25rem - 1px);border-top-right-radius: calc(0.25rem - 1px);" alt="{{ foto.titulo }}">
            </div>
            <button type="submit" class="custom-button">Editar Produto</button>
        </form>
    </div>
{% endblock %}
        